// Just throws an error.

export function run(): void {
    throw new Error("error thrown");
}
